### ISSUE TITLE
Routing Error

### ISSUE THREAD

**Issue by hopewise** [adexin/refinerycms-videojs#17]
I just installed the gem, and restarted rails, when I click on the "Add Video" in the page editor, I get this error:

Routing Error

refinery/videos/insert
Try running rake routes for more information on available routes.

I am mounting RefineryCMS at routes.rb like this:

mount Refinery::Core::Engine, :at => '/cms'

My admin page:
http://0.0.0.0:3000/cms/refinery

Notice that 
http://0.0.0.0:3000/cms/refinery/videos/insert 
works fine, but the video link (http://0.0.0.0:3000/refinery/videos/insert ) at the editor missing the 'cms' where Refinery is mounted .. how can I solve this?

Thanks.

**Comment by adexin-team** [comment]
As of refinerycms >=4.0.2 you could use `config/initializers/refinery/core.rb` for that, e.g.
```ruby
# Specify a different Refinery::Core::Engine mount path than the default of "/".
# Make sure you clear the `tmp/cache` directory after changing this setting.
config.mounted_path = "/cms"
```
