### ISSUE TITLE
Videos with a link source

### ISSUE THREAD

**Issue by joekur** [adexin/refinerycms-videojs#18]
Hey, I've encountered some problems when trying out the demo site. Embedded file videos seem to be working, but those with link sources don't appear to be working at all.

I'm not sure if this link will stay up, but here's an example page: http://refinerycms-videojs-demo.herokuapp.com/refinery/pages/beatles/edit

For one, when I add the video, all the content in the editor becomes hidden/invisible. And when viewing the page, the content is there with the video box, but the video does not actually work. This seems to be the case with all link-sourced videos.

**Comment by adexin-team** [comment]
Fixed in version >= 0.6.1
