### ISSUE TITLE
Video from source file not showing after save

### ISSUE THREAD

**Issue by Kardans** [adexin/refinerycms-videojs#19]
Hello,

I'm using refinerycms-videojs 0.5.5.1. When I upload video file, add it to page with WYMeditor and save, it's disappeared on next open. In HTML editor I see this:

<video id="video_5" class="video-js vjs-default-skin" data-setup=" {&quot;autoplay&quot;: false,&quot;controls&quot;: true,&quot;preload&quot;: true,&quot;loop&quot;: true}"></video>

There are also only video player skin on public side. What could be the problem?

**Comment by adexin-team** [comment]
Fixed in version >=0.6.1
