### ISSUE TITLE
rails g refinery:videos command line failed - Dragonfly::App is deprecated

### ISSUE THREAD

**Issue by awongCM** [adexin/refinerycms-videojs#22]
Hi,

I'm trying to test out your refinerycm-videojs plugin.

After following the instructions, I tried executing the following command line.

rails g refinery:videos

I get the following errors.

andy@LINUXAWCM:~/Projects/Ruby/refinerycms$ rails g refinery:videos
/home/andy/.rvm/gems/ruby-2.1.1/gems/dragonfly-1.0.5/lib/dragonfly/app.rb:33:in `[]': Dragonfly::App[:refinery_videos] is deprecated - use Dragonfly.app (for the default app) or Dragonfly.app(:refinery_videos) (for extra named apps) instead. See docs at http://markevans.github.io/dragonfly for details (RuntimeError)
    from /home/andy/.rvm/gems/ruby-2.1.1/gems/dragonfly-1.0.5/lib/dragonfly.rb:27:in`[]'
    from /home/andy/.rvm/gems/ruby-2.1.1/bundler/gems/refinerycms-videojs-54078087d6d4/config/routes.rb:2:in `block in <top (required)>'
    from /home/andy/.rvm/gems/ruby-2.1.1@global/gems/actionpack-4.1.1/lib/action_dispatch/routing/mapper.rb:526:in`instance_exec'
    from /home/andy/.rvm/gems/ruby-2.1.1@global/gems/actionpack-4.1.1/lib/action_dispatch/routing/mapper.rb:526:in `block in with_default_scope'
    from /home/andy/.rvm/gems/ruby-2.1.1@global/gems/actionpack-4.1.1/lib/action_dispatch/routing/mapper.rb:740:in`scope'
    from /home/andy/.rvm/gems/ruby-2.1.1@global/gems/actionpack-4.1.1/lib/action_dispatch/routing/mapper.rb:525:in `with_default_scope'
    from /home/andy/.rvm/gems/ruby-2.1.1@global/gems/actionpack-4.1.1/lib/action_dispatch/routing/route_set.rb:333:in`eval_block'
    from /home/andy/.rvm/gems/ruby-2.1.1@global/gems/actionpack-4.1.1/lib/ac

Looking at the errors, my first suspect was that I had to install dragonfly gem (which I didn't have in the beginning).  

I did gem install dragonfly, and then in Gemfile, gem dragonfly, '~>1.0.5'.

and then do the rails generate command again.

Still the same problem.

What else do I need to do in order to get the video plugin to work?

**Comment by felix-digitalkarma** [comment]
I'm having the same issue. Did you get any closer with this ?

**Comment by antonmi** [comment]
Sorry, guys, I don't support the gem. Please, see forks.

**Comment by adexin-team** [comment]
Fixed in version >=0.6.0
